### ISSUE TITLE
Challenge List offers a problem which has already been solved

### ISSUE THREAD

**Issue by ivan100sic** [polarity-cf/arugo#11]
The problem in question was 1213E. I solved it over two years ago but it still appeared in the Challenge List.

**Comment by ivan100sic** [comment]
The issue is probably a consequence of this:
https://github.com/polarity-cf/arugo/blob/6a6387cbb27d4efd56a997ca547873003fd101c7/base/util.py#L173

I made a lot more than 3000 submissions :)

**Comment by polarity-cf** [comment]
Thank you for reporting this. I will raise the limit now.
