### ISSUE TITLE
Solution is not validated even though the problem was solved

### ISSUE THREAD

**Issue by ivan100sic** [polarity-cf/arugo#12]
I solved CF problem 260E, and although I tried to validate my solution nothing happens.
This could possibly be due to CF API failure. Arugo should be more resillient in that case.

**Comment by polarity-cf** [comment]
Sorry I will investigate into this asap

**Comment by polarity-cf** [comment]
I will make an option to quit a challenge then >_<

**Comment by polarity-cf** [comment]
:( For now I can only prevent users from taking new challenge when the API is down, and provide the option to discard the challenge.
